name: Gradle Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: epa tests
        run: ./gradlew epa:test
      - name: ui tests
        run: xvfb-run ./gradlew ui:test

  build-linux:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Linux distributable
        run: ./gradlew packageReleaseDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: linux-distributables
          path: ui/build/compose/binaries/main-release/deb/*.deb

  build-windows:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Windows distributable
        run: ./gradlew packageMsi
      - uses: actions/upload-artifact@v4
        with:
          name: windows-distributables
          path: ui\build\compose\binaries\main\msi\*.msi

  build-macOs:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build macOs distributable
        run: ./gradlew packageReleaseDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: macOs-distributables
          path: ui/build/compose/binaries/main-release/dmg/*.dmg