name: Gradle Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gmitch215/setup-java@6d2c5e1f82f180ae79f799f0ed6e3e5efb4e664d
        with:
          distribution: 'jetbrains'
          java-version: 21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: epa tests
        run: ./gradlew epa:test
      - name: ui tests
        run: xvfb-run ./gradlew ui:test

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gmitch215/setup-java@6d2c5e1f82f180ae79f799f0ed6e3e5efb4e664d
        with:
          distribution: 'jetbrains'
          java-version: 21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Linux distributable
        run: ./gradlew packageReleaseDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: linux-distributables
          path: ui/build/compose/binaries/main/*/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gmitch215/setup-java@6d2c5e1f82f180ae79f799f0ed6e3e5efb4e664d
        with:
          distribution: 'jetbrains'
          java-version: 21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Windows distributable
        run: ./gradlew packageMsi packageExe
      - uses: actions/upload-artifact@v4
        with:
          name: windows-distributables
